name: CI Pipeline immotech

on: 
  push: 
    branches: 
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    
    # - name: Install denpendencies
    #   run: yarn 

    - name: Run lint
      run: yarn run lint

    # - name: Run tests
    #   run: yarn test

    # - name: Build
    #   run: yarn run re:build